# Generated by Django 5.2.7 on 2025-10-23 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe comenzar con 2 (casa) o 9 (móvil) y tener 9 digitos.', regex='^[29]\\d{8}$')])),
                ('correo', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='Correo inválido')])),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
    ]
